name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worksheet3_backend
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (backend)
        run: npm install

      - name: Run tests (backend)
        run: npm test

      - name: Build (backend)
        run: npm run build

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worksheet3_frontend
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (frontend)
        run: npm install

      - name: Run tests (frontend)
        run: npm test

      - name: Build (frontend)
        run: npm run build
